### ISSUE TITLE
Error when running fMoW Temporal Generation 

### ISSUE THREAD

**Issue by Hrsh-Venket** [samar-khanna/DiffusionSat#13]
When I run

`./launch_scripts/launch_fmow_temporal_md_controlnet.sh launch_accelerate_configs/single_gpu_accelerate_config.yaml`

I get the following

```shell
(diffusionsat) [hrsh.venket_asp25@master DiffusionSat]$ ./launch_scripts/launch_fmow_temporal_md_controlnet.sh launch_accelerate_configs/single_gpu_accelerate_config.yaml
/home/hrsh.venket_asp25/DiffusionSat/src/diffusers/models/cross_attention.py:30: FutureWarning: Importing from cross_attention is deprecated. Please import from diffusers.models.attention_processor instead.
  deprecate(
Using unet from ./diffusionsat_checkpoints/finetune_sd21_sn-satlas-fmow_snr5_md7norm_bs64/checkpoint-100000/
10/08/2024 17:13:19 - INFO - __main__ - Distributed environment: NO
Num processes: 1
Process index: 0
Local process index: 0
Device: cpu

Mixed precision type: fp16

wandb: Using wandb-core as the SDK backend. Please refer to https://wandb.me/wandb-core for more information.
wandb: W&B API key is configured. Use `wandb login --relogin` to force relogin
wandb: ERROR failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
Traceback (most recent call last):
  File "/home/hrsh.venket_asp25/DiffusionSat/train_controlnet.py", line 1343, in <module>
    main(args)
  File "/home/hrsh.venket_asp25/DiffusionSat/train_controlnet.py", line 646, in main
    wandb.init(project=args.wandb)
  File "/home/hrsh.venket_asp25/.conda/envs/diffusionsat/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1266, in init
    wandb._sentry.reraise(e)
  File "/home/hrsh.venket_asp25/.conda/envs/diffusionsat/lib/python3.10/site-packages/wandb/analytics/sentry.py", line 155, in reraise
    raise exc.with_traceback(sys.exc_info()[2])
  File "/home/hrsh.venket_asp25/.conda/envs/diffusionsat/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 1252, in init
    return wi.init()
  File "/home/hrsh.venket_asp25/.conda/envs/diffusionsat/lib/python3.10/site-packages/wandb/sdk/wandb_init.py", line 844, in init
    raise error
wandb.errors.errors.CommError: failed to upsert bucket: returned error 401 Unauthorized: {"errors":[{"message":"user is not logged in","path":["upsertBucket"],"extensions":{"code":"PERMISSION_ERROR"}}],"data":{"upsertBucket":null}}
Traceback (most recent call last):
  File "/home/hrsh.venket_asp25/.conda/envs/diffusionsat/bin/accelerate", line 8, in <module>
    sys.exit(main())
  File "/home/hrsh.venket_asp25/.conda/envs/diffusionsat/lib/python3.10/site-packages/accelerate/commands/accelerate_cli.py", line 45, in main
    args.func(args)
  File "/home/hrsh.venket_asp25/.conda/envs/diffusionsat/lib/python3.10/site-packages/accelerate/commands/launch.py", line 979, in launch_command
    simple_launcher(args)
  File "/home/hrsh.venket_asp25/.conda/envs/diffusionsat/lib/python3.10/site-packages/accelerate/commands/launch.py", line 628, in simple_launcher
    raise subprocess.CalledProcessError(returncode=process.returncode, cmd=cmd)
subprocess.CalledProcessError: Command '['/home/hrsh.venket_asp25/.conda/envs/diffusionsat/bin/python', 'train_controlnet.py', '--wandb=finetune_controlnet', '--pretrained_model_name_or_path=stabilityai/stable-diffusion-2-1', '--unet_path=./diffusionsat_checkpoints/finetune_sd21_sn-satlas-fmow_snr5_md7norm_bs64/checkpoint-100000/', '--dataset=fmow_temporal', '--shardlist=./webdataset_shards/fmow_temporal_shardlist_disk.txt', '--num_metadata=7', '--num_cond=3', '--temporal', '--temporal_attn', '--resolution=256', '--train_batch_size=16', '--gradient_accumulation_steps=1', '--gradient_checkpointing', '--max_train_steps=40000', '--checkpointing_steps=5000', '--checkpoint_preempt_steps=250', '--learning_rate=2e-05', '--max_grad_norm=1', '--lr_scheduler=constant', '--lr_warmup_steps=0', '--output_dir=./outputs/controlnet3d-mixattn_sd21_md7norm_fmow_temporal', '--resume_from_checkpoint=latest']' returned non-zero exit status 1.
(diffusionsat) [hrsh.venket_asp25@master DiffusionSat]$
``` 

How do I manage the W&B Authentication error here? I don't have access to the API.

**Comment by House-yuyu** [comment]
@Hrsh-Venket hi,  may i ask how do you generate 'fMoW_train.csv' for training?

**Comment by Hrsh-Venket** [comment]
My mistake. I understood that this was the method to run your model on your test dataset. How do you recommend I run it?

**Comment by Hrsh-Venket** [comment]
Misread the readme! Was trying to run the model with pretrained weights. Understood.
